### ISSUE TITLE
Doesn't seem to work on Grav 1.7.0-rc.10 and Admin 1.10.0-rc.10

### ISSUE THREAD

**Issue by OrthoCube** [getgrav/grav-plugin-auto-date#8]
I tried creating a page and the current date is not automatically set. Tried saving the page and there is still no date.

However, I did try running it on Grav 1.6.25 and Admin 1.9.14 and creating a page (even without saving) automatically sets the current date in the frontmatter.

Is this an incompatibility issue? Can I fix the problem myself?

**Comment by mahagr** [comment]
I think this one is related to https://github.com/trilbymedia/grav-plugin-flex-objects/issues/58

Try disabling the Pages from the Flex Object plugin and see if the logic still works with the old pages.

**Comment by ricardo118** [comment]
yeah it just needs to add flex pages support

**Comment by ricardo118** [comment]
cant seem to be able to assign myself to it

**Comment by mahagr** [comment]
Likely fixed in https://github.com/getgrav/grav/commit/3a05dcf6592dc9855bfea05c14171500923a3849

**Comment by mahagr** [comment]
@OrthoCube Can you test again?

**Comment by biozic** [comment]
It still doesn't work for me (Grav v1.7.0-rc.15 - Admin v1.10.0-rc.15) with flex-object pages, though it does work with old page system.

**Comment by paulrudy** [comment]
Just tried it myself in Grav v1.7.0-rc.19, and doesn't work.

**Comment by jgonyea** [comment]
FYI, I think this is still broken.

**Comment by paulrudy** [comment]
Still broken. Perhaps the plugin should not be included in official plugins until/unless it works with 1.7?

**Comment by paulrudy** [comment]
Still broken in Grav 1.7.5. This would be very useful to have working again. Perhaps remove from the plugin directory until it's fixed?

**Comment by mahagr** [comment]
Fixed in https://github.com/trilbymedia/grav-plugin-flex-objects/commit/e5bce26be8392afb10d71c62eeb1ad5c432f7d39
